services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: 4dm1n
      WORDPRESS_DB_PASSWORD: cM01LeB055
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: 4dm1n
      MYSQL_PASSWORD: cM01LeB055
      MYSQL_RANDOM_ROOT_PASSWORD: '0'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
